export const entity = {
  USER: 'USER',
  OTP: 'OTP',
  ROLE: 'ROLE',
  PERMISSION: 'PERMISSION',
  MESSAGE: 'MESSAGE',
  CONVERSATION: 'CONVERSATION',
  NOTIFICATION: 'NOTIFICATION',
  CREDENTIALS:"CREDENTIALS",
  PLANS: "RAZORPAY#PLANS",
  TRANSACTIONS: "TRANSACTIONS",
  SUBSCRIPTION:"SUBSCRIPTION",
  ACTIVE_PLAN:"ACTIVE_PLAN"
};
